version: "3.6"

services:

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata



  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
      - .env
    logging:
      driver: none


  
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    command: /start-reload.sh
    ports:
      - "8888:80"
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}





volumes:
  app-db-data:
  pgadmin-data:

