# @Author: Rafael Direito
# @Date:   2023-05-22 11:50:38
# @Last Modified by:   Pedro Ferreira
# @Last Modified time: 2024-02-22 16:33:41
version: "3.9"

services:

  db:
    image: postgres:12
    command: -c shared_buffers=256MB -c max_connections=200
    profiles: [ "debug", "dev" ]
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    profiles: [ "debug" ]
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
      - .env
    logging:
      driver: none

  mongo:
    image: mongo:4.4.10
    profiles: [ "debug", "dev" ]
    volumes:
      - app-mongo-db-data:/data/db
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    profiles: [ "debug" ]
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "${MONGO_EXPRESS_ENABLE_ADMIN}"

  report:
    image: '${DOCKER_IMAGE_REPORT?Variable not set}:${TAG-latest}'
    profiles: [ "debug", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/shared
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile.report
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    env_file:
      - .env

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    profiles: [ "debug", "dev" ]
    command: /start-reload.sh
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./backend/app:/app
      - shared-data:/shared
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      report:
        condition: service_healthy

volumes:
  app-db-data:
  pgadmin-data:
  app-mongo-db-data:
  shared-data:
  rabbitmq-data:
  rabbitmq-logs:
