version: "3.9"

services:

  db:
    image: postgres:12
    command: -c shared_buffers=256MB -c max_connections=200
    profiles: ["debug", "dev"]
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata



  pgadmin:
    image: dpage/pgadmin4
    profiles: ["debug"]
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
      - .env
    logging:
      driver: none

  mongo:
    image: mongo:4.4.10
    profiles: ["debug", "dev"]
    volumes:
      - app-mongo-db-data:/data/db
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    profiles: ["debug"]
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/

  
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    profiles: ["debug", "dev"]
    command: /start-reload.sh
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    extra_hosts:
      - "host.docker.internal:host-gateway"





volumes:
  app-db-data:
  pgadmin-data:
  app-mongo-db-data:

