FROM python:3.9

COPY ./report-app/src /app/src
COPY /report-app/requirements.txt /app

WORKDIR /app

RUN pip3 install -r requirements.txt

EXPOSE 3000

CMD ["uvicorn",  "--reload", "src.main:app", "--host=0.0.0.0", "--port=3000"]