#Deriving the latest base image
FROM python:3.8.10

# Setting the working directory
WORKDIR /app/

#to COPY the remote file at working directory in container
COPY ./producer/emit_data.py ./

RUN apt-get update && apt-get install -y \
    python3-pip

COPY /producer/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt;

CMD [ "python3", "./emit_data.py"]